//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace PWorlds.Gen
{
	public class MapSize
	{
		public static int TINY = 32;
		public static int SMALL = 64;
		public static int MEDIUM = 128;
		public static int LARGE = 256;
		public static int HUGE = 512;
	}
}

