//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using UnityEngine;

using LibNoise;
using LibNoise.Generator;
using LibNoise.Operator;

namespace PWorlds.Gen.Biomes
{
	public class Biome
	{
		public float sampleSizeX {get; set;}
		public float sampleSizeY {get; set;}

		public float sampleOffsetX {get; set;}
		public float sampleOffsetY {get; set;}

		public int numModules {get; set;}

		public int numOctaves {get; set;}
		public float frequency {get; set;}
		public float persistence {get; set;}

		//Map Colors
		public Color topColor {get; set;}
		public Color bottomColor {get; set;}

		//Number of divisions in this type of map
		public int numDivisions {get; set;}

		//Height multiplier for the map, to make it taller or shorter
		public float heightMultiplier {get; set;}

		//Water variables
		public bool hasWater {get; set;}
		//Rather than using a water height, I will use increments 
		public int waterLevel {get; set;}
		public Color waterColor {get; set;}

		public virtual void init(){

		}
	}
}

